FROM rust:1.59

# Create a new project in order to avoid building dependencies every time
RUN USER=root cargo new --bin pub-sub-rust
WORKDIR /pub-sub-rust

# Copy cargo files to new project
COPY ./Cargo.lock ./Cargo.lock
COPY ./Cargo.toml ./Cargo.toml

# Build step to cache dependencies, as long as the cargo files above have not changed
RUN cargo build --release
RUN rm src/*.rs

# Copy source tree
COPY ./src ./src

# Build for release
RUN rm ./target/release/deps/pub_sub_rust*
RUN cargo build --release

CMD ["./target/release/pub-sub-rust"]